#!/usr/bin/env php
<?php

$phar = \Phar::running(TRUE);
if ($phar)
{
    require_once "$phar/vendor/autoload.php";
}
else
{
    // Look for the autoloader in various places, and load the first one we
    // find.
    $autoloaders = [
        'Drupal root' => 'autoload.php',
        'Drupal root or repository root' => 'vendor/autoload.php',
        'Repository root' => 'docroot/vendor/autoload.php',
    ];
    $autoloaders = array_filter($autoloaders, 'file_exists');
    require_once reset($autoloaders);
}

$out = new \Symfony\Component\Console\Output\ConsoleOutput();

$status = \Robo\Robo::run(
    $_SERVER['argv'],
    ['\Acquia\Lightning\Commands\RoboFile'],
    'Lightning',
    '0.0.0',
    $out,
    'acquia/lightning_dev'
);
exit($status);
