#!/usr/bin/env php
<?php

$phar = \Phar::running(TRUE);
if ($phar)
{
    require_once "$phar/vendor/autoload.php";
}
else
{
    // Running in the Drupal root.
    if (file_exists('autoload.php'))
    {
        require_once 'autoload.php';
    }

    // Running in the repository root.
    else if (file_exists('vendor/autoload.php'))
    {
        require_once 'vendor/autoload.php';
    }
}

$out = new \Symfony\Component\Console\Output\ConsoleOutput();

$status = \Robo\Robo::run(
    $_SERVER['argv'],
    ['\Acquia\Lightning\Commands\RoboFile'],
    'Lightning',
    '0.0.0',
    $out,
    'acquia/lightning_dev'
);
exit($status);
