#!/usr/bin/env php
<?php

$phar = \Phar::running(TRUE);
if ($phar)
{
    require_once "$phar/vendor/autoload.php";
}
else
{
    $path = ['docroot', 'vendor', 'autoload.php'];

    while ($path)
    {
        $autoload = implode('/', $path);

        if (file_exists($autoload))
        {
            require_once $autoload;
            break;
        }
        else
        {
            array_shift($path);
        }
    }
}

$out = new \Symfony\Component\Console\Output\ConsoleOutput();

$status = \Robo\Robo::run(
    $_SERVER['argv'],
    ['\Acquia\Lightning\Commands\RoboFile'],
    'Lightning',
    '0.0.0',
    $out,
    'acquia/lightning_dev'
);
exit($status);
